Controllers/GüvenlikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OgrenciBilgiSistemi.Models;
using System.ComponentModel;

namespace OgrenciBilgiSistemi.Controllers
{
    public class GüvenlikController : Controller
    {
        // GET: Güvenlik
        nottakipEntities1 db = new nottakipEntities1();
        public ActionResult GirisYap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GirisYap(kullanıcı_ogretmen r)
        {
            var bilgiler = db.kullanıcı_ogretmen
                .FirstOrDefault(x => x.KullaniciAd == r.KullaniciAd && x.KullanıcıSifre == r.KullanıcıSifre);
            if (bilgiler != null)
            {
                Session["KullaniciAd"] = bilgiler.KullaniciAd.ToString();
                Session["KullanıcıSifre"] = bilgiler.KullanıcıSifre.ToString();
                return RedirectToAction("ogretmenilkekran", "ogretmen");
            }
            else
            {
              
               return Content("<script language='javascript' type='text/javascript'>" +   
                    "alert('Kullanıcı Adınızı veya Sifrenizi yanliş girdiniz.');</script>");
            }

        }

        public ActionResult OgrenciGirisYap()
        {
            return View();
        }
        [HttpPost]
       

        public ActionResult OgrenciGirisYap(kullanıcı_ogrenci t)
        {
            var bilgiler1 = db.kullanıcı_ogrenci
                .FirstOrDefault(x => x.OgrenciNo == t.OgrenciNo && x.KullanıcıSifre == t.KullanıcıSifre);
            ViewBag.OgrenciNo = t.OgrenciNo;
            if (bilgiler1 != null)
            {
                Session["OgrenciNo"] = bilgiler1.OgrenciNo.ToString();
                Session["KullanıcıSifre"] = bilgiler1.KullanıcıSifre.ToString();
               

                return RedirectToAction("ogrencifiltrele", "ogretmen",new { id=ViewBag.OgrenciNo}); 
              
            }
            else
            {
                return Content("<script language='javascript' type='text/javascript'>" +
                   "alert('Kullanıcı Adınızı veya Sifrenizi yanliş girdiniz.');</script>");
            }

        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OgrenciBilgiSistemi.Models;

namespace OgrenciBilgiSistemi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult acilisekranı()
        {
            return View();
        }
        public ActionResult bakımdaekranı()
        {
            return View();
        }
        public ActionResult Ogretmenlayoutbakımdaekranı()
        {
            return View();
        }
        OgrenciOgretmenbaglanti model = new OgrenciOgretmenbaglanti();
        nottakipEntities1 db = new nottakipEntities1();
        baglanti cs = new baglanti();
        public ActionResult ogretmendropdown()
        {
            cs.ogrenciList = new SelectList(db.ogrenci, "ogrenci_numara", "ogrenci_adı");
            cs.ogretmenList = new SelectList(db.ogretmen, "id   ", "Ders_Adı");

            return View(cs);
        }
          
        public JsonResult GetogretmenList(int p)
        {
            var itemlist = (from x in db.ogretmen
                           join y in db.ogrenci on x.ogrenci.ogrenci_numara equals y.ogrenci_numara
                           where x.ogrenci.ogrenci_numara == p
                           select new
                           {
                               Text = x.Ders_Adı,
                               Value = x.id.ToString()
                           } ).ToList();
                         

            return Json(itemlist, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "Ogrenci/Ogretmen Giriş Paneli";
}

<div class="jumbotron">
    <h1>Ogrenci/Ogretmen Giriş Paneli</h1>

</div>

<div class="row">
    <div class="col-md-4">
        <h2>@Html.ActionLink("OgrenciGirişi", "OgrenciGirisYap", "Güvenlik")</h2>
        <p>
            
        </p>
    </div>
    <div class="col-md-4">
        <h2>@Html.ActionLink("OgretmenGirişi", "GirisYap", "Güvenlik")</h2>
        <p></p>
    </div>
  
</div>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Home/Ogretmenlayoutbakımdaekranı.cshtml
@{
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}


<!--
Author: W3layouts
Author URL: http://w3layouts.com
-->
<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>Bicycle Error Page Responsive Widget Template :: W3layouts</title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8" />
    <meta name="keywords"
          content="Bicycle Error Page Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
    </script>
    <!-- //Meta tag Keywords -->
    <!--/Style-CSS -->
    <link rel="stylesheet" href="~/web404/css/style.css" type="text/css" media="all" />
    <!--//Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="~/web404/css/font-awesome.css" rel="stylesheet">
    <!-- //font-awesome-icons -->
</head>

<body>
    <section class="w3l-error-61-404">
        <!-- /error-61-section -->
        <div class="error-61-mian">
            <div class="wrapper">
                <div class="errors-16-top">
                    <div class="errors-16-info">
                        <h3> BAKIMDA </h3>
                        
                        <p>Bu Sayfa Şuan  Yapim Aşamasinda</p>
                       

                    </div>

                </div>
                <div class="copyright-footer">
                    <div class="copy-right">
                        <p>

                            <a </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- //error-61-section -->
</body>

</html>

Views/Home/bakımdaekranı.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!--
Author: W3layouts
Author URL: http://w3layouts.com
-->
<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>Bicycle Error Page Responsive Widget Template :: W3layouts</title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8" />
    <meta name="keywords"
          content="Bicycle Error Page Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
    </script>
    <!-- //Meta tag Keywords -->
    <!--/Style-CSS -->
    <link rel="stylesheet" href="~/web404/css/style.css" type="text/css" media="all" />
    <!--//Style-CSS -->
    <!-- font-awesome-icons -->
    <link href="~/web404/css/font-awesome.css" rel="stylesheet">
    <!-- //font-awesome-icons -->
</head>

<body>
    <section class="w3l-error-61-404">
        <!-- /error-61-section -->
        <div class="error-61-mian">
            <div class="wrapper">
                <div class="errors-16-top">
                    <div class="errors-16-info">
                        <h3> BAKIMDA </h3>

                        <p>Bu Sayfa Şuan  Yapim Aşamasinda</p>


                    </div>

                </div>
                <div class="copyright-footer">
                    <div class="copy-right">
                        <p>
                           
                            <a </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- //error-61-section -->
</body>

</html>

Views/Home/ogretmendropdown.cshtml
@model OgrenciBilgiSistemi.Models.baglanti
@{
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    $(function () {
        $('#dropogrenci').change(function () {
            var id = $('#dropogrenci').val();
            $.ajax({
                url: '/Home/GetogretmenList',
                data: { p: id },
                type= "POST",
                dataType: "Json",

                success: function (data) {
                    console.log(data);
                    $('#dropogretmen').empty();
                    for (var i = 0; i < data.length; i++) {
                        $('#dropogretmen').append("<option value ='" +
                            data[i].Value + "'>" + data[i].Text + "</Option>");
                    }
                }
            });

        });

    });
</script>

<div>
    <h3>Ogrenci-ogretmen</h3>
</div>
<div style="margin-left:50px">
    @Html.Label("ogrenci")
    @Html.DropDownList("dropogrenci", Model.ogrenciList, "--ogrenci", new { @class = "form-control" })
    <br />
    @Html.Label("ogretmen")
    @Html.DropDownList("dropogretmen", Model.ogretmenList, "--ogretmenler", new { @class = "form-control" })
</div>