Models/ogretmen.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ogretmen
    {
        public int id { get; set; }
        [DisplayName("Öğrenci numara")]
        public Nullable<int> ogrenci_numara { get; set; }
        [DisplayName("Ders Kodu")]
        public Nullable<int> Ders_Kodu { get; set; }
        [DisplayName("Ders Adı")]
        public string Ders_Adı { get; set; }
        [DisplayName(" Vize Notu")]
        public Nullable<byte> Vize_Notu { get; set; }
        [DisplayName(" Final Notu")]
        public byte Final_Notu { get; set; }
    
        public virtual ogrenci ogrenci { get; set; }
    }
}

Controllers/ogretmenController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OgrenciBilgiSistemi.Models;
using System.Linq.Dynamic.Core;

namespace OgrenciBilgiSistemi.Controllers
{

    public class ogretmenController : Controller
    {
        private nottakipEntities1 db = new nottakipEntities1();
       
        

        // GET: ogretmen

        public ActionResult Index()
        {
            var ogretmen = db.ogretmen.Include(o => o.ogrenci);
            return View(ogretmen.ToList());
        }

        // GET: ogretmen/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ogretmen ogretmen = db.ogretmen.Find(id);
            if (ogretmen == null)
            {
                return HttpNotFound();
            }
            return View(ogretmen);
        }

        // GET: ogretmen/Create
        public ActionResult Create()
        {
            ViewBag.ogrenci_numara = new SelectList(db.ogrenci, "ogrenci_numara", "ogrenci_adı");
            return View();
        }

        // POST: ogretmen/Create
        // Aşırı gönderim saldırılarından korunmak için, bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için bkz. https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,ogrenci_numara,Ders_Kodu,Ders_Adı,Vize_Notu,Final_Notu")] ogretmen ogretmen)
        {
            if (ModelState.IsValid)
            {
                db.ogretmen.Add(ogretmen);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ogrenci_numara = new SelectList(db.ogrenci, "ogrenci_numara", "ogrenci_adı", ogretmen.ogrenci_numara);
            return View(ogretmen);
        }

        // GET: ogretmen/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ogretmen ogretmen = db.ogretmen.Find(id);
            if (ogretmen == null)
            {
                return HttpNotFound();
            }
            ViewBag.ogrenci_numara = new SelectList(db.ogrenci, "ogrenci_numara", "ogrenci_adı", ogretmen.ogrenci_numara);
            return View(ogretmen);
        }

        // POST: ogretmen/Edit/5
        // Aşırı gönderim saldırılarından korunmak için, bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için bkz. https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,ogrenci_numara,Ders_Kodu,Ders_Adı,Vize_Notu,Final_Notu")] ogretmen ogretmen)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ogretmen).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ogrenci_numara = new SelectList(db.ogrenci, "ogrenci_numara", "ogrenci_adı", ogretmen.ogrenci_numara);
            return View(ogretmen);
        }

        // GET: ogretmen/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ogretmen ogretmen = db.ogretmen.Find(id);
            if (ogretmen == null)
            {
                return HttpNotFound();
            }
            return View(ogretmen);
        }

        // POST: ogretmen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ogretmen ogretmen = db.ogretmen.Find(id);
            db.ogretmen.Remove(ogretmen);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


            public ActionResult ogrencifiltrele(int id)
            {
                string ogrenciismi = (from k in db.ogrenci
                                      where k.ogrenci_numara == id
                                      select k.ogrenci_adı).FirstOrDefault();
                ViewBag.Title = ogrenciismi + " dersler ve notlar ";
                ViewBag.Id = id;
                List<ogretmen> filtreliogrenci = (from u in db.ogretmen
                                                  where u.ogrenci_numara == id
                                                  select u).ToList();
                return View(filtreliogrenci);
            }
        public ActionResult ogretmenilkekran()

        {
            ViewBag.OnlineUyeSayisi = HttpContext.Application["OnlineUyeSayisi"];
            return View();
        }
        public ActionResult ogrenciilkekran()

        {
            ViewBag.OnlineUyeSayisi = HttpContext.Application["OnlineUyeSayisi"];
            return View();
        }
        public ActionResult cokkieolustur()

        {
            HttpCookie cookiekullanıcı = new HttpCookie("kullanici", "zeynep");
            HttpContext.Response.Cookies.Add(cookiekullanıcı);
            ViewBag.Kullanici = HttpContext.Request.Cookies["kullanici"].Value;
            
            return View();
        }
        public ActionResult cokkiesil()
        {
            HttpContext.Request.Cookies.Remove("kullanici"); 
            return View();
        }

        public ActionResult webgrid()
        {
            var info = new List<ogretmen>();
            using(nottakipEntities1 db = new nottakipEntities1())
            {
                info = db.ogretmen.ToList();
            }
            return View(info);
        }
        public ActionResult gridsearch(string sort= "Ders_Adı",string sortdir="asc",string search="")
        {
            int totalRecord = 0;
            var data = Getsıralama(search, sort, sortdir, out totalRecord);
            ViewBag.Totalrows = totalRecord;
            ViewBag.search = search;

            return View(data);
        }
        public List<ogretmen> Getsıralama(string search, string sort, string sortdir, out
int totalRecord)
        {
            //burada AlbümEntities veritabanı içeriğini oluşturmaktadır
            using (nottakipEntities1 db = new nottakipEntities1())
            {
                var v = (from a in db.ogretmen
                         where

                         a.Ders_Adı.Contains(search)  
                         


                         select a
                );
                totalRecord = v.Count();
                v = v.OrderBy(sort + " " + sortdir);
                return v.ToList();
            }
        }
        OgrenciOgretmenbaglanti model = new OgrenciOgretmenbaglanti();
        public ActionResult ogretmendropdown()
        {
            List<ogrenci> ogrenciList = db.ogrenci.OrderBy(f => f.ogrenci_adı).ToList();
            model.ogrenciList = (from u in ogrenciList
                              select new SelectListItem
                              {
                                  Text = u.ogrenci_adı,
                                  Value = u.ogrenci_numara.ToString()

                              }
                            ).ToList();
            return View(model);
        }
        [HttpPost]
        public JsonResult GetogretmenList(int id)
        {
            List<ogretmen> ogretmenList = db.ogretmen.Where(f => f.ogrenci_numara == id).OrderBy(f => f.Ders_Adı).ToList();
            List<SelectListItem> itemlist = (from s in ogretmenList
                                             select new SelectListItem
                                             {
                                                 Text = s.Ders_Adı,
                                                 Value = s.id.ToString()

                                             }).ToList();
            return Json(itemlist, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/ogretmen/Create.cshtml
@model OgrenciBilgiSistemi.Models.ogretmen

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ogretmen</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ogrenci_numara, "Ogrenci İsmi", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ogrenci_numara", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ogrenci_numara, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ders_Kodu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ders_Kodu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ders_Kodu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ders_Adı, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ders_Adı, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ders_Adı, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vize_Notu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vize_Notu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vize_Notu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Final_Notu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Final_Notu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Final_Notu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ekle" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Dön", "Index")
</div>

Views/ogretmen/Delete.cshtml
@model OgrenciBilgiSistemi.Models.ogretmen

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>ogretmen</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Ders_Kodu)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Ders_Kodu)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Ders_Adı)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Ders_Adı)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Vize_Notu)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Vize_Notu)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Final_Notu)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Final_Notu)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ogrenci.ogrenci_adı)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ogrenci.ogrenci_adı)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Views/ogretmen/Details.cshtml
@model OgrenciBilgiSistemi.Models.ogretmen

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>ogretmen</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Ders_Kodu)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Ders_Kodu)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Ders_Adı)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Ders_Adı)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Vize_Notu)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Vize_Notu)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Final_Notu)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Final_Notu)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ogrenci.ogrenci_adı)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ogrenci.ogrenci_adı)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Views/ogretmen/Edit.cshtml
@model OgrenciBilgiSistemi.Models.ogretmen

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>ogretmen</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.ogrenci_numara, "ogrenci_numara", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ogrenci_numara", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ogrenci_numara, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Ders_Kodu, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ders_Kodu, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ders_Kodu, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Ders_Adı, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ders_Adı, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ders_Adı, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Vize_Notu, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Vize_Notu, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Vize_Notu, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Final_Notu, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Final_Notu, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Final_Notu, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/ogretmen/Index.cshtml
@model IEnumerable<OgrenciBilgiSistemi.Models.ogretmen>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ders_Kodu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ders_Adı)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vize_Notu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Final_Notu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ogrenci.ogrenci_adı)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ders_Kodu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ders_Adı)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vize_Notu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Final_Notu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ogrenci.ogrenci_adı)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
                @Html.ActionLink("Details", "Details", new { id=item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

Views/ogretmen/cokkieolustur.cshtml
@{
    Layout = null;
}

<h2>@ViewBag.Kullanici</h2>

Views/ogretmen/cokkiesil.cshtml
@{
    Layout = null;
}

<h2>@ViewBag.Kullanici</h2>

Views/ogretmen/gridsearch.cshtml
@model List<OgrenciBilgiSistemi.Models.ogretmen>

@{
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
    var ornekgrid = new WebGrid(source: Model, canPage: true, rowsPerPage: 30);
    ornekgrid.Pager(WebGridPagerModes.All);

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>gridsearch</title>
</head>
<body>
    <h2>Öğrenci Not Bilgisi Arama</h2>
    <h3> Toplam kayıt Sayısı : @ViewBag.TotalRows</h3>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="collapse navbar-collapse">
                @using (Html.BeginForm("gridsearch", "ogretmen", FormMethod.Get, new { @class = "navbar-form navbar left " }))
                {
                    <div class="form-group">
                        <input type="text" name="search" value="@ViewBag.search" class="form-control" placeholder="Ara" />

                    </div>

                    <button type="submit" value="ARA" class="btn fa fa-search"></button>
                }

            </div>
        </div>

    </nav>
    <style type="text/css">
        .webgrid-table {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            font-size: 1.2em;
            width: 100%;
            display: table;
            border-collapse: separate;
            border: solid 1px #98BF21;
            background-color: white;
        }

            .webgrid-table td, th {
                border: 1px solid #98BF21;
                padding: 3px 7px 2px;
            }

        .webgrid-header {
            background-color: #A7C942;
            color: #FFFFFF;
            padding-bottom: 4px;
            padding-top: 5px;
            text-align: left;
        }

        .webgrid-footer {
        }

        .webgrid-row-style {
            padding: 3px 7px 2px;
        }

        .webgrid-alternating-row {
            background-color: #EAF2D3;
            padding: 3px 7px 2px;
        }
    </style>
    <div id="content">
        @ornekgrid.GetHtml(
        tableStyle: "webgrid-table",
        headerStyle: "webgrid-header",
        footerStyle: "webgrid-footer",
        alternatingRowStyle: "webgrid-alternating-row",
        rowStyle: "webgrid-row-style",
        columns: ornekgrid.Columns(
       ornekgrid.Column(columnName: "ogrenci_numara", header: "Öğrenci numara:"),
    ornekgrid.Column(columnName: "Ders_Kodu", header: "Ders Kodu:"),
    ornekgrid.Column(columnName: "Ders_Adı", header: "Ders Adı:"),
    ornekgrid.Column(columnName: "Vize_Notu", header: "Vize Notu:"),
    ornekgrid.Column(columnName: "Final_Notu", header: "Final Notu:")
   


    ))
    </div>
    <!--
       <div>

           @ornekgrid.Table(
            tableStyle: "table table-responsive table-bordered",
        columns: ornekgrid.Columns(
    ornekgrid.Column(columnName: "ogrenci_numara", header: "ögrenci_numara"),
    ornekgrid.Column(columnName: "Ders_Kodu", header: "Ders_Kodu"),
    ornekgrid.Column(columnName: "Ders_Adı", header: "Ders_Adı"),
    ornekgrid.Column(columnName: "Vize_Notu", header: "Vize_Notu"),
    ornekgrid.Column(columnName: "Final_Notu", header: "Final_Notu")
    ))

       </div>
        -->
</body>
</html>

Views/ogretmen/ogrencifiltrele.cshtml
@model IEnumerable<OgrenciBilgiSistemi.Models.ogretmen>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Ogrencilerin Listesi";
    var ornekgrid = new WebGrid(source: Model, canPage: true, rowsPerPage:15);
    ornekgrid.Pager(WebGridPagerModes.All);
}

@if (Session["OgrenciNo"] != null)
{
    <text>
        <h1>Hoşgeldin @Session["OgrenciNo"].ToString()</h1>


    </text>
}
<h2>Not Bilgi Ekranı</h2>
<style type="text/css">
    .webgrid-table {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        font-size: 1.2em;
        width: 100%;
        display: table;
        border-collapse: separate;
        border: solid 1px #98BF21;
        background-color: white;
    }

        .webgrid-table td, th {
            border: 1px solid #98BF21;
            padding: 8px 9px 4px;
        }

    .webgrid-header {
        background-color: #A7C942;
        color: #FFFFFF;
        padding-bottom: 6px;
        padding-top: 7px;
        text-align: left;
    }

    .webgrid-footer {
    }

    .webgrid-row-style {
        padding: 3px 7px 2px;
    }

    .webgrid-alternating-row {
        background-color: #EAF2D3;
        padding: 3px 7px 2px;
    }
</style>
<div id="content">
    @ornekgrid.GetHtml(
    tableStyle: "webgrid-table",
    headerStyle: "webgrid-header",
    footerStyle: "webgrid-footer",
    alternatingRowStyle: "webgrid-alternating-row",
    rowStyle: "webgrid-row-style",
    columns: ornekgrid.Columns(
ornekgrid.Column(columnName: "ogrenci_numara", header: "Öğrenci numara"),
ornekgrid.Column(columnName: "Ders_Kodu", header: "Ders Kodu"),
ornekgrid.Column(columnName: "Ders_Adı", header: "Ders Adı"),
ornekgrid.Column(columnName: "Vize_Notu", header: "Vize Notu"),
ornekgrid.Column(columnName: "Final_Notu", header: "Final Notu"),
ornekgrid.Column(columnName: "ogrenci.ogrenci_adı", header: "Öğrenci adı")
    


))
</div>

Views/ogretmen/ogretmendropdown.cshtml
@model OgrenciBilgiSistemi.Models.OgrenciOgretmenbaglanti


<br />
@using (Html.BeginForm("Create", "ogretmen", FormMethod.Post))
{

    <div class="container">

        <div class="form-group">
            @Html.DropDownListFor(Model => Model.ogrenci_numara, Model.ogrenciList, "--ogrenciSeçin--", new { @class = "form-control" })

        </div>

    </div>

    <div class="container">

        <div class="form-group">
            @Html.DropDownListFor(Model => Model.ogretmenID, new SelectList(""), "--ogretmen secin--", new { @class = "form-control" })

        </div>

    </div>

}

<html>
<body>



    @section scripts
{


        <script type="text/javascript">
            $(document).ready(function () {

                $('#ogrenci_numara').change(function () {
                    var id = $(this).val();
                    var ogretmenList = $('#ogretmenID');
                    ogretmenList.empty();

                    $.ajax({
                        url: '/ogretmen/GetogretmenList',
                        type: 'POST',
                        dataType: 'json',
                        data: { 'id': id },
                        success: function (data) {
                            $.each(data, function (ogretmendropdown, option) {
                                ogretmenList.append('<option value =' + option.Value + '>' + option.Text + '</option>');

                            })

                        }


                    });


                });

            });



        </script>

    }
</body>
</html>